# Generated by Django 4.0.4 on 2022-06-07 14:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Tag',
            },
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('is_enabled', models.BooleanField(default=False)),
                ('cost', models.DecimalField(decimal_places=3, default=0, max_digits=6)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tag', models.ManyToManyField(to='static_content.tag')),
            ],
            options={
                'verbose_name': 'Media',
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('uri', models.CharField(max_length=500)),
                ('format', models.CharField(choices=[('png', 'image/png'), ('jpg', 'image/jpg'), ('jpeg', 'image/jpeg'), ('gif', 'image/gif'), ('mp4', 'video/mp4'), ('webm', 'video/webm'), ('x-m4v', 'video/x-m4v'), ('quicktime', 'video/quicktime'), ('x-wav', 'audio/x-wav'), ('mp3', 'audio/mp3'), ('mpeg', 'audio/mpeg')], max_length=10)),
                ('media', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='static_content.media')),
            ],
            options={
                'verbose_name': 'Media attachment',
            },
        ),
    ]
