# Generated by Django 4.0.4 on 2022-06-07 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('static_content', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='media',
            old_name='tag',
            new_name='tags',
        ),
        migrations.AlterField(
            model_name='media',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
