# Generated by Django 4.0.4 on 2022-06-07 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('static_content', '0002_rename_tag_media_tags_alter_media_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='media',
            name='tags',
            field=models.ManyToManyField(related_name='media', to='static_content.tag'),
        ),
    ]
