# Generated by Django 4.0.4 on 2022-06-11 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('static_content', '0006_alter_media_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='media',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='media',
            name='tags',
            field=models.ManyToManyField(null=True, related_name='media', to='static_content.tag'),
        ),
    ]
