# Generated by Django 4.0.4 on 2022-06-12 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('static_content', '0007_media_is_approved_media_is_published_and_more'),
        ('static_content', '0010_alter_attachment_type'),
    ]

    operations = [
    ]
