# Generated by Django 4.0.4 on 2022-06-12 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('static_content', '0011_merge_20220612_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='format',
            field=models.CharField(choices=[('png', 'png'), ('jpg', 'jpg'), ('jpeg', 'jpeg'), ('gif', 'gif'), ('mp4', 'mp4'), ('webm', 'webm'), ('x-m4v', 'x-m4v'), ('quicktime', 'quicktime'), ('x-wav', 'x-wav'), ('mp3', 'mp3'), ('mpeg', 'mpeg')], max_length=100),
        ),
    ]
