# Generated by Django 4.0.4 on 2022-06-14 11:51

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('static_content', '0014_alter_media_is_enabled'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='order',
            unique_together={('buyer', 'media')},
        ),
    ]
