# Generated by Django 4.0.4 on 2022-06-16 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('static_content', '0015_alter_order_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
    ]
