# Generated by Django 4.0.4 on 2022-08-24 16:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('static_content', '0017_ratings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratings',
            name='stars',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)]),
        ),
    ]
